# Generated by Django 5.0.4 on 2024-04-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
